//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiedPiperIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart_view
    {
        public Nullable<int> id { get; set; }
        public Nullable<int> prdouct_id { get; set; }
        public string product_name { get; set; }
        public int session_id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<double> taxable_price { get; set; }
        public Nullable<int> category { get; set; }
    }
}
