//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiedPiperIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int Order_ID { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Product_List { get; set; }
        public Nullable<double> totalprice { get; set; }
        public Nullable<double> taxableprice { get; set; }
        public Nullable<int> order_number { get; set; }
    }
}
